src/StopReasons/Pages/Index.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

using CSharpFunctionalExtensions;

using StopReasons.Config;
using StopReasons.Services;
using System;

namespace StopReasons.Pages;

public class IndexModel : PageModel
{
    private readonly AvailabilityStateManager _availabilityState;
    private readonly ServiceToFilterDevicesByLineOfBusiness _serviceToFilterDevicesByLine;
    private const string _downtimeReasonDropDownPrefix = "drdd_";
    private const string _downtimeReasonCheckBoxPrefix = "drcb_";
    private const int _defaultPageSize = 10;

    public PendingDowntimePeriodToSetReasonsForViewModel[] DowntimePeriodsPerDevice;
    public readonly List<(string ReasonText, string ReasonCode)> ValidReasons = new();
    public readonly List<string> LineOfBusinesses = new();

    [FromForm(Name= "cpn")]
    public int CurrentPageNumber { get; set; }

    public sealed record PageNumberInfo(string PageLabel, int PageNumber, bool IsItCurrentPageSelected)
    {
        public static PageNumberInfo From(int number, int currentPage) =>
            new(PageLabel: number.ToString(), PageNumber: number, IsItCurrentPageSelected: currentPage == number);
    }

    public List<PageNumberInfo> PageNumbersToDisplay { get; set; }

    [FromForm(Name = "cps")]
    public int CurrentPageSize { get; set; }

    [FromForm(Name = "cls")]
    public string CurrentLineSelected { get; set; } = "-";

    public IndexModel(ILogger<IndexModel> logger, AvailabilityStateManager availabilityState, IOptions<DowntimeReasonsConfig> config,
        ServiceToFilterDevicesByLineOfBusiness serviceToFilterDevicesByLine)
    {
        this._availabilityState = availabilityState;
        this._serviceToFilterDevicesByLine = serviceToFilterDevicesByLine;
        this.ValidReasons = config.Value.AllowedReasons.Select(o => (ReasonText: o.Text, ReasonCode: o.Code)).ToList();
        this.LineOfBusinesses = this._serviceToFilterDevicesByLine.ListAllLineOfBusiness();
    }

    public async Task<IActionResult> OnGet()
    {
        CurrentPageNumber = 1;
        CurrentPageSize = _defaultPageSize;

        await SetDowntimePeriodsToDisplay();

        return Page();
    }

    public async Task<IActionResult> OnPostSpecificPageNumber(int number)
    {
        CurrentPageNumber = number;

        await SetDowntimePeriodsToDisplay();

        return Page();
    }

    public async Task<IActionResult> OnPostSpecificPageSize(int size)
    {
        CurrentPageSize = size;
        CurrentPageNumber = 1;  // when changing page size, go back to first page

        await SetDowntimePeriodsToDisplay();

        return Page();
    }

    public async Task<IActionResult> OnPostSpecificDevicesInLine(string linename)
    {
        CurrentPageSize = _defaultPageSize;
        CurrentPageNumber = 1;
        CurrentLineSelected = linename;

        await SetDowntimePeriodsToDisplay();

        return Page();
    }

    public async Task<IActionResult> OnPostSaveReasonsIndividuallyAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        foreach(var reasonDropDownFieldName in GetFieldNamesOfReasonDropdowns())
        {
            var maybeReason = TryGetReason(setInDropDownWithName: reasonDropDownFieldName);
            if(maybeReason.HasNoValue)
                continue;

            await SaveReason(forFieldName: reasonDropDownFieldName, reasonToSet: maybeReason.Value);
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSaveReasonsMassivelyAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        var maybeReasonToSetMassively = TryGetReason(setInDropDownWithName: "ddlReasonToSetMassively");
        if (maybeReasonToSetMassively.HasNoValue)
            return RedirectToPage();

        foreach (var reasonCheckBoxFieldName in GetFieldNamesOfReasonCheckBoxes())
        {
            await SaveReason(forFieldName: reasonCheckBoxFieldName, reasonToSet: maybeReasonToSetMassively.Value);
        }

        return RedirectToPage();
    }

    private async Task SetDowntimePeriodsToDisplay()
    {
        var response = await _availabilityState.GetPendingDowntimePeriodsToSetReasonsFor(withParams: new(
            PageNumber: CurrentPageNumber,
            PageSize: CurrentPageSize,
            SortingColumn: "period_start",
            SortingDirection: "desc",
            maybeFilterByTheseDeviceIds: CurrentLineSelected == "-" ? [] : _serviceToFilterDevicesByLine.ListDeviceIds(boundToLineOfBusiness: CurrentLineSelected)
        ));

        DowntimePeriodsPerDevice = response.StopingPeriods.Select(MapToViewModel).ToArray();
        PageNumbersToDisplay = GetPageNumbersToDisplay(fromNumberOfPagesRetrieved: response.NumberOfPages, withCurrentPageNumberSelected: CurrentPageNumber).ToList();
    }

    private static IEnumerable<int> GetSequenceWhenPageCountIsLessThanMaxPagesThatCanBeDisplayed(int fromNumberOfPagesRetrieved) =>
        Enumerable.Range(start: 1, count: fromNumberOfPagesRetrieved);

    private static IEnumerable<int> GetSequenceForFirstLeftSegment(int maxNumberOfPageNumbersThatCanBeDisplayed) =>
        Enumerable.Range(start: 1, count: maxNumberOfPageNumbersThatCanBeDisplayed);

    private static IEnumerable<int> GetSequenceForLastSegmentAtTheRight(int fromNumberOfPagesRetrieved, int maxNumberOfPageNumbersThatCanBeDisplayed) =>
        Enumerable.Range(start: fromNumberOfPagesRetrieved - maxNumberOfPageNumbersThatCanBeDisplayed + 1, count: maxNumberOfPageNumbersThatCanBeDisplayed);

    private static IEnumerable<int> GetSequenceForMiddleSegment(int withCurrentPageNumberSelected, int maxNumberOfPageNumbersThatCanBeDisplayed) =>
        Enumerable.Range(start: withCurrentPageNumberSelected - (maxNumberOfPageNumbersThatCanBeDisplayed / 2), count: maxNumberOfPageNumbersThatCanBeDisplayed);

    private static IEnumerable<PageNumberInfo> GetPageNumbersToDisplay(int fromNumberOfPagesRetrieved, int withCurrentPageNumberSelected)
    {
        const int maxNumberOfPageNumbersThatCanBeDisplayed = 10;
        const int minPagesLeftAtTheRightSide = 2;

        var areThereLessPagesThanMaxPageCountThatCanBeDisplayed = fromNumberOfPagesRetrieved <= maxNumberOfPageNumbersThatCanBeDisplayed;
        var isCurrentPageAtTheFirstLeftSegment = areThereLessPagesThanMaxPageCountThatCanBeDisplayed == false && withCurrentPageNumberSelected <= maxNumberOfPageNumbersThatCanBeDisplayed - minPagesLeftAtTheRightSide;
        var isCurrentPageAtMiddleSegment = isCurrentPageAtTheFirstLeftSegment == false && withCurrentPageNumberSelected <= fromNumberOfPagesRetrieved - (maxNumberOfPageNumbersThatCanBeDisplayed / 2);
        var isCurrentPageAtLastSegmentToTheRight = isCurrentPageAtMiddleSegment == false && withCurrentPageNumberSelected > fromNumberOfPagesRetrieved - (maxNumberOfPageNumbersThatCanBeDisplayed / 2);

        Func<int, PageNumberInfo> _map = pageNumber => PageNumberInfo.From(number: pageNumber, currentPage: withCurrentPageNumberSelected);

        if (areThereLessPagesThanMaxPageCountThatCanBeDisplayed)
        {
            foreach (var pageInfo in GetSequenceWhenPageCountIsLessThanMaxPagesThatCanBeDisplayed(fromNumberOfPagesRetrieved).Select(_map))
                yield return pageInfo;
        }
        else
        {
            yield return new(PageLabel: "|<<", PageNumber: 1, IsItCurrentPageSelected: false);

            if (isCurrentPageAtTheFirstLeftSegment)
                foreach (var pageInfo in GetSequenceForFirstLeftSegment(maxNumberOfPageNumbersThatCanBeDisplayed).Select(_map)) yield return pageInfo;
            
            if(isCurrentPageAtMiddleSegment)
                foreach (var pageInfo in GetSequenceForMiddleSegment(withCurrentPageNumberSelected, maxNumberOfPageNumbersThatCanBeDisplayed).Select(_map)) yield return pageInfo;

            if(isCurrentPageAtLastSegmentToTheRight)
                foreach (var pageInfo in GetSequenceForLastSegmentAtTheRight(fromNumberOfPagesRetrieved, maxNumberOfPageNumbersThatCanBeDisplayed).Select(_map)) yield return pageInfo;
            
            yield return new(PageLabel: ">>|", PageNumber: fromNumberOfPagesRetrieved, IsItCurrentPageSelected: false);
        }
    }

    private Maybe<string> TryGetReason(string setInDropDownWithName)
    {
        var maybeValueSetInDropDown = (string) Request.Form[setInDropDownWithName];
        return string.IsNullOrEmpty(maybeValueSetInDropDown)
            ? Maybe<string>.None
            : maybeValueSetInDropDown;
    }

    private static PendingDowntimePeriodToSetReasonsForViewModel MapToViewModel(AvailabilityStateManager.PendingDowntimePeriodToSetReasonsFor from) =>
        new PendingDowntimePeriodToSetReasonsForViewModel(
            DeviceId: from.DeviceId,
            InitiallyStoppedAt: $"{from.InitiallyStoppedAt:MM/dd hh:mm:ss tt}",
            LastStopReportedAt: $"{from.LastStopReportedAt:MM/dd hh:mm:ss tt}",
            ReasonDropDownFieldName: $"{_downtimeReasonDropDownPrefix}{from.DowntimePeriodId}",
            ReasonCheckBoxFieldName: $"{_downtimeReasonCheckBoxPrefix}{from.DowntimePeriodId}",
            _sourceRecord: from);

    private async Task SaveReason(string forFieldName, string reasonToSet)
    {
        var downtimePeriodId = long.Parse(forFieldName.Split('_')[1]);

        await _availabilityState.SetDowntimeReason(
            reason: reasonToSet,
            forDowntimePeriodId: downtimePeriodId);

        System.Console.WriteLine($"Period reason set successfully for '{downtimePeriodId}' downtime period id");
    }


src/StopReasons/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Razones de Paro";
}

<form method="post">
    <table style="width: 100%">
        <tr>
            <td style="width: 100%">
                Filtre eventos de dispositivos por Línea:
                <table>
                    <tr>
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentLineSelected == "-" ? "btn-primary" : "btn-outline-primary")" value="Todas las Líneas" asp-page-handler="SpecificDevicesInLine" asp-route-linename="-" /></td>
                        @foreach (var lineName in Model.LineOfBusinesses)
                        {
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentLineSelected == lineName ? "btn-primary" : "btn-outline-primary")" value=@lineName asp-page-handler="SpecificDevicesInLine" asp-route-linename=@lineName /></td>
                        }
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br />

    @if (Model.DowntimePeriodsPerDevice.Any())
    {
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Establecer esta razón para todas las filas seleccionadas abajo</h5>
            <select name="ddlReasonToSetMassively">
                <option value="">Por favor seleccione una razón para establecer en forma masiva</option>
                @foreach (var validReason in Model.ValidReasons)
                {
                <option value=@validReason.ReasonCode>@validReason.ReasonCode - @validReason.ReasonText</option>
                }
            </select>
            &nbsp;&nbsp;
            <input class="btn btn-warning btn-lg" type="submit" onclick="return confirm('Está seguro de querer establecerle esta misma razón a todos los períodos seleccionados abajo?')" value="Establecer esta razón en forma masiva" asp-page-handler="SaveReasonsMassively" title="Establecer esta razón para todas las filas seleccionadas abajo" />
        </div>
    </div>

    <table class="table table-striped" data-toggle="table" data-search="true" data-search-highlight="true">
        <thead>
            <tr>
                <th data-sortable="true">Dispositivo</th>
                <th data-sortable="true">Paro desde</th>
                <th data-sortable="true">Más reciente Paro</th>
                <th>Razón de Paro</th>
                <th style="width: 10px"/>
            </tr>
        </thead>
        <tbody>
            @foreach (var period in Model.DowntimePeriodsPerDevice)
            {
            <tr>
                <td>@period.DeviceId</td>
                <td>@period.InitiallyStoppedAt</td>
                <td>@period.LastStopReportedAt</td>
                <td>
                    <select name=@period.ReasonDropDownFieldName>
                        <option value="">Por favor seleccione una razón</option>
                        @foreach (var validReason in Model.ValidReasons)
                        {
                            <option value=@validReason.ReasonCode>@validReason.ReasonCode - @validReason.ReasonText</option>
                        }
                    </select>
                </td>
                <td><input class="form-check-input" type="checkbox" name=@period.ReasonCheckBoxFieldName /></td>
            </tr>
            }
        </tbody>
    </table>

    <br />
    <table style="width: 100%">
        <tr>
            <td style="width: 50%">
                Escoja la página que quiere ver:
                <table>
                    <tr>
                        @foreach (var pageInfo in Model.PageNumbersToDisplay)
                        {
                        <td><input type="submit" class="btn btn-sm @(pageInfo.IsItCurrentPageSelected ? "btn-primary" : "btn-outline-primary")" value=@pageInfo.PageLabel asp-page-handler="SpecificPageNumber" asp-route-number=@pageInfo.PageNumber /></td>
                        }
                    </tr>
                </table>
            </td>
            <td style="width: 50%" align="right">
                Escoja el tamaño de Página: 
                <table>
                    <tr>
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentPageSize == 10 ? "btn-primary" : "btn-outline-primary")" value="10" asp-page-handler="SpecificPageSize" asp-route-size="10" /></td>
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentPageSize == 50 ? "btn-primary" : "btn-outline-primary")" value="50" asp-page-handler="SpecificPageSize" asp-route-size="50" /></td>
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentPageSize == 100 ? "btn-primary" : "btn-outline-primary")" value="100" asp-page-handler="SpecificPageSize" asp-route-size="100" /></td>
                        <td><input type="submit" class="btn btn-sm @(Model.CurrentPageSize == 200 ? "btn-primary" : "btn-outline-primary")" value="200" asp-page-handler="SpecificPageSize" asp-route-size="200" /></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
        
    <br />
    <input class="btn btn-primary btn-lg" type="submit" value="Almacenar estas razones en forma individual" asp-page-handler="SaveReasonsIndividually" />
    }
    else
    {
    <div class="alert alert-success" role="alert">No hay paros de dispositivos pendientes a establecerles sus motivo @(Model.CurrentLineSelected != "-" ? "(en la linea filtrada)" : "(en todas las lineas)")</div>
    }

    <input type="hidden" name="cpn" value=@Model.CurrentPageNumber />
    <input type="hidden" name="cps" value=@Model.CurrentPageSize />
    <input type="hidden" name="cls" value=@Model.CurrentLineSelected />
</form>